# Stage 1: Build React App
FROM docker.io/node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve dengan Nginx
FROM docker.io/nginx:alpine
# --- BARIS BARU: Copy nginx.conf ---
COPY nginx.conf /etc/nginx/conf.d/default.conf
# -----------------------------------
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]