# Containerfile.backend
FROM docker.io/node:20-alpine

WORKDIR /app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install --production

# Copy semua fail backend (since context is now ./backend)
COPY . .

# Default Env (boleh di-override semasa podman run)
ENV PORT=5000
ENV MONGO_URI=mongodb://localhost:27017/ikmb-dashboard

EXPOSE 5000

CMD ["node", "server.js"]